di::uniba::map::b::adventure::type::AdvObjectContainer
List<AdvObject> di.uniba.map.b.adventure.type.AdvObjectContainer.list
boolean di.uniba.map.b.adventure.type.AdvObjectContainer.open
di.uniba.map.b.adventure.type.AdvObjectContainer.AdvObjectContainer(int id)
id
di.uniba.map.b.adventure.type.AdvObjectContainer.AdvObjectContainer(int id, String name)
id name
di.uniba.map.b.adventure.type.AdvObjectContainer.AdvObjectContainer(int id, String name, String description)
id name description
di.uniba.map.b.adventure.type.AdvObjectContainer.AdvObjectContainer(int id, String name, String description, Set< String > alias)
id name description alias
List< AdvObject > di.uniba.map.b.adventure.type.AdvObjectContainer.getList()
Referenced by di.uniba.map.b.adventure.impl.OpenObserver.openObject.
void di.uniba.map.b.adventure.type.AdvObjectContainer.setList(List< AdvObject > list)
list
void di.uniba.map.b.adventure.type.AdvObjectContainer.add(AdvObject o)
o
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.init.
void di.uniba.map.b.adventure.type.AdvObjectContainer.remove(AdvObject o)
o
boolean di.uniba.map.b.adventure.type.AdvObjectContainer.isOpen()
Referenced by di.uniba.map.b.adventure.impl.UseObserver.update.
void di.uniba.map.b.adventure.type.AdvObjectContainer.setOpen(boolean open)
open
Referenced by di.uniba.map.b.adventure.impl.OpenObserver.openObject, di.uniba.map.b.adventure.impl.UseObserver.update.
boolean di.uniba.map.b.adventure.type.AdvObjectContainer.setOpen()