di::uniba::map::b::adventure::parser::ParserOutput
Command di.uniba.map.b.adventure.parser.ParserOutput.command
AdvObject di.uniba.map.b.adventure.parser.ParserOutput.object
AdvObject di.uniba.map.b.adventure.parser.ParserOutput.invObject
di.uniba.map.b.adventure.parser.ParserOutput.ParserOutput(Command command, AdvObject object)
command object
di.uniba.map.b.adventure.parser.ParserOutput.ParserOutput(Command command, AdvObject object, AdvObject invObejct)
command object invObejct
Command di.uniba.map.b.adventure.parser.ParserOutput.getCommand()
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.nextMove, di.uniba.map.b.adventure.impl.InventoryObserver.update, di.uniba.map.b.adventure.impl.KillObserver.update, di.uniba.map.b.adventure.impl.LookAtObserver.update, di.uniba.map.b.adventure.impl.MoveObserver.update, di.uniba.map.b.adventure.impl.OpenObserver.update, di.uniba.map.b.adventure.impl.PickUpObserver.update, di.uniba.map.b.adventure.impl.PushObserver.update, di.uniba.map.b.adventure.impl.ReadObserver.update, di.uniba.map.b.adventure.impl.UseObserver.update.
void di.uniba.map.b.adventure.parser.ParserOutput.setCommand(Command command)
command
AdvObject di.uniba.map.b.adventure.parser.ParserOutput.getObject()
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.nextMove, di.uniba.map.b.adventure.impl.OpenObserver.update, di.uniba.map.b.adventure.impl.PickUpObserver.update, di.uniba.map.b.adventure.impl.PushObserver.update, di.uniba.map.b.adventure.impl.ReadObserver.update.
void di.uniba.map.b.adventure.parser.ParserOutput.setObject(AdvObject object)
object
AdvObject di.uniba.map.b.adventure.parser.ParserOutput.getInvObject()
Referenced by di.uniba.map.b.adventure.impl.OpenObserver.update, di.uniba.map.b.adventure.impl.ReadObserver.update, di.uniba.map.b.adventure.impl.UseObserver.update.
void di.uniba.map.b.adventure.parser.ParserOutput.setInvObject(AdvObject invObject)
invObject