di::uniba::map::b::adventure::GameDescription
final List<Room> di.uniba.map.b.adventure.GameDescription.rooms
final List<Command> di.uniba.map.b.adventure.GameDescription.commands
List<AdvObject> di.uniba.map.b.adventure.GameDescription.inventory
Room di.uniba.map.b.adventure.GameDescription.currentRoom
boolean di.uniba.map.b.adventure.GameDescription.keyUsed
final List<AdvObject> di.uniba.map.b.adventure.GameDescription.allObjects
List< Room > di.uniba.map.b.adventure.GameDescription.getRooms()
Returns the list of rooms in the game. List of Room objects
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.init.
void di.uniba.map.b.adventure.GameDescription.setCurrentRoomById(int roomId)
Sets the current room based on the provided room ID. roomId ID of the room to set as the current room
void di.uniba.map.b.adventure.GameDescription.setGame(int roomId, List< Integer > inventoryIds, boolean monsterAlive, boolean isDoorOpen)
Sets up the game state based on the provided parameters. roomId ID of the current room inventoryIds List of IDs for objects in the player's inventory monsterAlive Flag indicating if the monster is alive isDoorOpen Flag indicating if a door is open
References di.uniba.map.b.adventure.GameDescription.getObjectById, di.uniba.map.b.adventure.GameDescription.setKeyUsed, di.uniba.map.b.adventure.type.AdvObject.setOpenable.
List< Command > di.uniba.map.b.adventure.GameDescription.getCommands()
Returns the list of commands available in the game. List of Command objects
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.init.
Room di.uniba.map.b.adventure.GameDescription.getCurrentRoom()
Returns the current room where the player is located. Current Room object
Referenced by di.uniba.map.b.adventure.Engine.execute, di.uniba.map.b.adventure.impl.SpaceEscape.nextMove, di.uniba.map.b.adventure.impl.OpenObserver.openObject, di.uniba.map.b.adventure.impl.KillObserver.update, di.uniba.map.b.adventure.impl.LookAtObserver.update, di.uniba.map.b.adventure.impl.MoveObserver.update, di.uniba.map.b.adventure.impl.PickUpObserver.update, di.uniba.map.b.adventure.impl.PushObserver.update, di.uniba.map.b.adventure.impl.UseObserver.update.
boolean di.uniba.map.b.adventure.GameDescription.isKeyUsed()
Returns whether a key has been used in the game. true if the key has been used, false otherwise
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.nextMove, di.uniba.map.b.adventure.impl.UseObserver.update.
void di.uniba.map.b.adventure.GameDescription.setKeyUsed(boolean keyUsed)
Sets the flag indicating whether a key has been used in the game. keyUsed true to indicate the key has been used, false otherwise
Referenced by di.uniba.map.b.adventure.GameDescription.setGame, di.uniba.map.b.adventure.impl.UseObserver.update.
void di.uniba.map.b.adventure.GameDescription.setCurrentRoom(Room currentRoom)
Sets the current room where the player is located. currentRoom The Room object to set as the current room
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.init, di.uniba.map.b.adventure.impl.SpaceEscape.nextMove, di.uniba.map.b.adventure.impl.MoveObserver.update.
List< AdvObject > di.uniba.map.b.adventure.GameDescription.getInventory()
Returns the player's inventory. List of AdvObject objects in the player's inventory
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.nextMove, di.uniba.map.b.adventure.impl.InventoryObserver.update, di.uniba.map.b.adventure.impl.KillObserver.update, di.uniba.map.b.adventure.impl.PickUpObserver.update, di.uniba.map.b.adventure.impl.PushObserver.update.
abstract void di.uniba.map.b.adventure.GameDescription.init()
Initializes the game. This method must be implemented by subclasses. Exception if an error occurs during initialization
Referenced by di.uniba.map.b.adventure.Engine.Engine.
abstract void di.uniba.map.b.adventure.GameDescription.nextMove(ParserOutput p, Window window)
Processes the player's next move based on the parsed input and updates the game state accordingly. This method must be implemented by subclasses. p The parsed player input window The game window for displaying output
abstract String di.uniba.map.b.adventure.GameDescription.getWelcomeMsg()
Returns the welcome message for the game. This method must be implemented by subclasses. The welcome message as a String
Referenced by di.uniba.map.b.adventure.Engine.execute.
void di.uniba.map.b.adventure.GameDescription.addObject(AdvObject obj)
Adds an object to the list of all objects in the game. obj The AdvObject to add
Referenced by di.uniba.map.b.adventure.type.Room.addObject.
Optional< AdvObject > di.uniba.map.b.adventure.GameDescription.getObjectById(int id)
Retrieves an object by its ID from the list of all objects in the game. id The ID of the object to retrieve An Optional containing the AdvObject if found, or an empty Optional otherwise
Referenced by di.uniba.map.b.adventure.GameDescription.setGame.