di::uniba::map::b::adventure::type::Command
final CommandType di.uniba.map.b.adventure.type.Command.type
final String di.uniba.map.b.adventure.type.Command.name
Set<String> di.uniba.map.b.adventure.type.Command.alias
di.uniba.map.b.adventure.type.Command.Command(CommandType type, String name)
Constructs a Command with a specified type and name. This constructor initializes a command without any aliases. type The type of the command. name The primary name of the command.
Referenced by di.uniba.map.b.adventure.type.Command.equals.
di.uniba.map.b.adventure.type.Command.Command(CommandType type, String name, Set< String > alias)
Constructs a Command with a specified type, name, and set of aliases. This constructor allows for the initialization of a command with multiple names. type The type of the command. name The primary name of the command. alias A set of alternative names or aliases for the command.
String di.uniba.map.b.adventure.type.Command.getName()
Returns the primary name of the command. The primary name of the command.
Set< String > di.uniba.map.b.adventure.type.Command.getAlias()
Returns the set of aliases for the command. A set of alternative names or aliases for the command.
void di.uniba.map.b.adventure.type.Command.setAlias(Set< String > alias)
Sets the aliases for the command. alias A set of alternative names or aliases for the command.
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.init.
void di.uniba.map.b.adventure.type.Command.setAlias(String[] alias)
Sets the aliases for the command from an array of strings. This method converts the array into a set and assigns it to the command. alias An array of alternative names or aliases for the command.
CommandType di.uniba.map.b.adventure.type.Command.getType()
Returns the type of the command. The type of the command.
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.nextMove, di.uniba.map.b.adventure.impl.InventoryObserver.update, di.uniba.map.b.adventure.impl.KillObserver.update, di.uniba.map.b.adventure.impl.LookAtObserver.update, di.uniba.map.b.adventure.impl.MoveObserver.update, di.uniba.map.b.adventure.impl.OpenObserver.update, di.uniba.map.b.adventure.impl.PickUpObserver.update, di.uniba.map.b.adventure.impl.PushObserver.update, di.uniba.map.b.adventure.impl.ReadObserver.update, di.uniba.map.b.adventure.impl.UseObserver.update.
int di.uniba.map.b.adventure.type.Command.hashCode()
Generates a hash code for the command. The hash code is based primarily on the command's type. A hash code for the command.
boolean di.uniba.map.b.adventure.type.Command.equals(Object obj)
Compares this command to another object for equality. Two commands are considered equal if they have the same type. obj The object to compare with this command. true if the specified object is a command with the same type; false otherwise.
References di.uniba.map.b.adventure.type.Command.Command.