di::uniba::map::b::adventure::impl::Window
JPanel di.uniba.map.b.adventure.impl.Window.panel
JLabel di.uniba.map.b.adventure.impl.Window.currentBackground
JLabel di.uniba.map.b.adventure.impl.Window.labelNavicella
JLabel di.uniba.map.b.adventure.impl.Window.timePlay
JTextArea di.uniba.map.b.adventure.impl.Window.leaderBoard
JTextArea di.uniba.map.b.adventure.impl.Window.roomNameTextArea
JTextArea di.uniba.map.b.adventure.impl.Window.roomDescriptionTextArea
JTextArea di.uniba.map.b.adventure.impl.Window.startDescriptionTextArea
JTextArea di.uniba.map.b.adventure.impl.Window.messageTextArea
JTextField di.uniba.map.b.adventure.impl.Window.testo
JTextField di.uniba.map.b.adventure.impl.Window.testo2
JTextField di.uniba.map.b.adventure.impl.Window.testo3
JScrollPane di.uniba.map.b.adventure.impl.Window.scrollPane
AePlayWave di.uniba.map.b.adventure.impl.Window.sottofondo
RESTClient di.uniba.map.b.adventure.impl.Window.client
JButton di.uniba.map.b.adventure.impl.Window.pauseButton
JButton di.uniba.map.b.adventure.impl.Window.loadGameButton
JButton di.uniba.map.b.adventure.impl.Window.newGameButton
JButton di.uniba.map.b.adventure.impl.Window.exitAndSaveButton
JButton di.uniba.map.b.adventure.impl.Window.exitWithoutSaveButton
JButton di.uniba.map.b.adventure.impl.Window.showLeaderBoardButton
Image di.uniba.map.b.adventure.impl.Window.image
Image di.uniba.map.b.adventure.impl.Window.resizedImage
boolean di.uniba.map.b.adventure.impl.Window.isPaused
int di.uniba.map.b.adventure.impl.Window.elapsedSeconds
String di.uniba.map.b.adventure.impl.Window.timeString
String di.uniba.map.b.adventure.impl.Window.insertText
final ImageIcon di.uniba.map.b.adventure.impl.Window.resizedPortale
final ImageIcon di.uniba.map.b.adventure.impl.Window.resizedCorridoio
final ImageIcon di.uniba.map.b.adventure.impl.Window.resizedSalaComandi
final ImageIcon di.uniba.map.b.adventure.impl.Window.resizedLaboratorio
final ImageIcon di.uniba.map.b.adventure.impl.Window.resizedMotore
final ImageIcon di.uniba.map.b.adventure.impl.Window.resizedArmeria
final ImageIcon di.uniba.map.b.adventure.impl.Window.resizedAlieno
final ImageIcon di.uniba.map.b.adventure.impl.Window.resizedArchivio
final ImageIcon di.uniba.map.b.adventure.impl.Window.resizedPortaleAcceso
di.uniba.map.b.adventure.impl.Window.Window(GameDescription game, Parser parser)
Constructs the main game window, initializing UI components and setting up event listeners. game The game description, containing the state and logic of the adventure game. parser The parser used to interpret player commands.
void di.uniba.map.b.adventure.impl.Window.showStartDescription(String startDescription)
Displays the starting description of the game in a text area. startDescription The starting description text.
Referenced by di.uniba.map.b.adventure.Engine.execute.
void di.uniba.map.b.adventure.impl.Window.showRoomName(String roomName)
Updates and displays the name of the current room in a text area. roomName The name of the current room.
Referenced by di.uniba.map.b.adventure.Engine.execute, di.uniba.map.b.adventure.impl.SpaceEscape.nextMove.
void di.uniba.map.b.adventure.impl.Window.showRoomDescription(String roomDescription)
Updates and displays the description of the current room in a text area. roomDescription The description of the current room.
Referenced by di.uniba.map.b.adventure.Engine.execute, di.uniba.map.b.adventure.impl.SpaceEscape.nextMove.
void di.uniba.map.b.adventure.impl.Window.showMessage(String message)
Displays a message in a text area, typically used for feedback or game instructions. message The message to display.
Referenced by di.uniba.map.b.adventure.impl.SpaceEscape.nextMove.
void di.uniba.map.b.adventure.impl.Window.showLeaderBoard()
Fetches and displays the leaderboard from a RESTful service.
References di.uniba.map.b.adventure.impl.RESTClient.getLeaderboard.
String di.uniba.map.b.adventure.impl.Window.getInsertText()
Retrieves the text currently inserted by the player. The text inserted by the player.