.TH "di.uniba.map.b.adventure.GameObserver" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.GameObserver
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.InventoryObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.KillObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.LookAtObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.MoveObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.OpenObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.PickUpObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.PushObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.ReadObserver\fP, and \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.UseObserver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBupdate\fP (\fBGameDescription\fP description, \fBParserOutput\fP parserOutput, \fBWindow\fP window)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
sangiovannesi 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String di\&.uniba\&.map\&.b\&.adventure\&.GameObserver\&.update (\fBGameDescription\fP description, \fBParserOutput\fP parserOutput, \fBWindow\fP window)"

.PP
\fBParameters\fP
.RS 4
\fIdescription\fP 
.br
\fIparserOutput\fP 
.br
\fIwindow\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Implemented in \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.InventoryObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.KillObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.LookAtObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.MoveObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.OpenObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.PickUpObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.PushObserver\fP, \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.ReadObserver\fP, and \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.UseObserver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
