.TH "di.uniba.map.b.adventure.parser.Parser" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.parser.Parser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP (Set< String > stopwords)"
.br
.ti -1c
.RI "\fBParserOutput\fP \fBparse\fP (String command, List< \fBCommand\fP > commands, List< \fBAdvObject\fP > objects, List< \fBAdvObject\fP > inventory)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBParser\fP class is responsible for interpreting player commands within the game\&. It processes input strings, removing stopwords, and identifies commands and objects mentioned in the input\&. It supports simple sentences structured as <action> <object> <object>, with articles and prepositions being ignored\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "di\&.uniba\&.map\&.b\&.adventure\&.parser\&.Parser\&.Parser (Set< String > stopwords)"
Constructs a \fBParser\fP with a specified set of stopwords\&. 
.PP
\fBParameters\fP
.RS 4
\fIstopwords\fP A set of strings representing stopwords to be ignored during parsing\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBParserOutput\fP di\&.uniba\&.map\&.b\&.adventure\&.parser\&.Parser\&.parse (String command, List< \fBCommand\fP > commands, List< \fBAdvObject\fP > objects, List< \fBAdvObject\fP > inventory)"
Parses a player command, identifying the command and objects mentioned in the input\&. 
.PP
\fBParameters\fP
.RS 4
\fIcommand\fP The player command to parse\&. 
.br
\fIcommands\fP A list of commands to check against\&. 
.br
\fIobjects\fP A list of objects to check against\&. 
.br
\fIinventory\fP A list of objects in the player's inventory to check against\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A \fBParserOutput\fP object containing the identified command and objects\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
