.TH "di.uniba.map.b.adventure.impl.AePlayWave" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.impl.AePlayWave
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBPosition\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAePlayWave\fP (String wavfile)"
.br
.ti -1c
.RI "void \fBstopSound\fP ()"
.br
.ti -1c
.RI "synchronized void \fBstartSound\fP ()"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is designed to play sound files in a separate thread\&. It supports basic operations such as play, stop, and handling of audio pan (left, right, normal)\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "di\&.uniba\&.map\&.b\&.adventure\&.impl\&.AePlayWave\&.AePlayWave (String wavfile)"

.SH "Member Function Documentation"
.PP 
.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.AePlayWave\&.run ()"

.SS "synchronized void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.AePlayWave\&.startSound ()"

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.AePlayWave\&.stopSound ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
