.TH "di.uniba.map.b.adventure.impl.PickUpObserver" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.impl.PickUpObserver
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdi\&.uniba\&.map\&.b\&.adventure\&.GameObserver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBupdate\fP (\fBGameDescription\fP description, \fBParserOutput\fP parserOutput, \fBWindow\fP window)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Observer implementation for handling 'pick up' commands within the game\&. This observer allows players to pick up objects from the current room and add them to their inventory, provided the objects are pickupable\&. 
.SH "Member Function Documentation"
.PP 
.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.PickUpObserver\&.update (\fBGameDescription\fP description, \fBParserOutput\fP parserOutput, \fBWindow\fP window)"
Processes a 'pick up' command, attempting to add the specified object to the player's inventory\&. Verifies if the object is present in the current room and if it is pickupable\&. If successful, the object is removed from the room and added to the inventory, and a success message is returned\&. Otherwise, an appropriate failure message is generated\&.
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP The current state of the game, including the player's current room and inventory\&. 
.br
\fIparserOutput\fP The parsed output of the player's command, including the command type and targeted object\&. 
.br
\fIwindow\fP The game window where output messages are displayed\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A string message indicating the outcome of the 'pick up' command\&. 
.RE
.PP

.PP
Implements \fBdi\&.uniba\&.map\&.b\&.adventure\&.GameObserver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
