.TH "di.uniba.map.b.adventure.GameObservable" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.GameObservable
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.SpaceEscape\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBattach\fP (\fBGameObserver\fP o)"
.br
.ti -1c
.RI "void \fBdetach\fP (\fBGameObserver\fP o)"
.br
.ti -1c
.RI "void \fBnotifyObservers\fP (\fBWindow\fP window)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
sangiovannesi 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void di\&.uniba\&.map\&.b\&.adventure\&.GameObservable\&.attach (\fBGameObserver\fP o)"

.PP
\fBParameters\fP
.RS 4
\fIo\fP 
.RE
.PP

.PP
Implemented in \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.SpaceEscape\fP\&.
.SS "void di\&.uniba\&.map\&.b\&.adventure\&.GameObservable\&.detach (\fBGameObserver\fP o)"

.PP
\fBParameters\fP
.RS 4
\fIo\fP 
.RE
.PP

.PP
Implemented in \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.SpaceEscape\fP\&.
.SS "void di\&.uniba\&.map\&.b\&.adventure\&.GameObservable\&.notifyObservers (\fBWindow\fP window)"

.PP
\fBParameters\fP
.RS 4
\fIwindow\fP 
.RE
.PP

.PP
Implemented in \fBdi\&.uniba\&.map\&.b\&.adventure\&.impl\&.SpaceEscape\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
