.TH "di.uniba.map.b.adventure.impl.OpenObserver" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.impl.OpenObserver
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBdi\&.uniba\&.map\&.b\&.adventure\&.GameObserver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBupdate\fP (\fBGameDescription\fP description, \fBParserOutput\fP parserOutput, \fBWindow\fP window)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Observer implementation for handling 'open' commands within the game\&. This observer allows players to open objects or containers in the game environment, potentially revealing or releasing items contained within\&. 
.SH "Member Function Documentation"
.PP 
.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.OpenObserver\&.update (\fBGameDescription\fP description, \fBParserOutput\fP parserOutput, \fBWindow\fP window)"
Processes an 'open' command, attempting to open the specified object or container\&. If the object is openable and not already open, it is opened, and any contained items are moved to the current room\&. Messages are generated to inform the player of the action's outcome\&.
.PP
\fBParameters\fP
.RS 4
\fIdescription\fP The current state of the game, including the player's current room and inventory\&. 
.br
\fIparserOutput\fP The parsed output of the player's command, including the command type and targeted object\&. 
.br
\fIwindow\fP The game window where output messages are displayed\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A string message indicating the outcome of the 'open' command\&. 
.RE
.PP

.PP
Implements \fBdi\&.uniba\&.map\&.b\&.adventure\&.GameObserver\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
