.TH "di.uniba.map.b.adventure.impl.AePlayWave.Position" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.impl.AePlayWave.Position
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLEFT\fP"
.br
.ti -1c
.RI "\fBRIGHT\fP"
.br
.ti -1c
.RI "\fBNORMAL\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "di\&.uniba\&.map\&.b\&.adventure\&.impl\&.AePlayWave\&.Position\&.LEFT"

.SS "di\&.uniba\&.map\&.b\&.adventure\&.impl\&.AePlayWave\&.Position\&.NORMAL"

.SS "di\&.uniba\&.map\&.b\&.adventure\&.impl\&.AePlayWave\&.Position\&.RIGHT"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
