.TH "di.uniba.map.b.adventure.impl.Database" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.impl.Database
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDatabase\fP ()"
.br
.ti -1c
.RI "boolean \fBinsertNewData\fP ()"
.br
.ti -1c
.RI "String \fBgetNameById\fP (String id)"
.br
.ti -1c
.RI "String \fBgetDescriptionById\fP (String id)"
.br
.ti -1c
.RI "String \fBgetRoomLookById\fP (String id)"
.br
.ti -1c
.RI "boolean \fBupdateNameById\fP (String id, String newName)"
.br
.ti -1c
.RI "boolean \fBupdateDescriptionById\fP (String id, String newDescription)"
.br
.ti -1c
.RI "boolean \fBupdateRoomLookById\fP (String id, String newRoomLook)"
.br
.ti -1c
.RI "void \fBclose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class provides database operations for the adventure game\&. It handles connections to the database and provides methods to retrieve and update game data\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Database\&.Database ()"
Constructor for \fBDatabase\fP\&. Initializes the database connection using JDBC and H2 database\&. 
.SH "Member Function Documentation"
.PP 
.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Database\&.close ()"
Closes the database connection\&. 
.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Database\&.getDescriptionById (String id)"
Retrieves the description associated with a given ID from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP The ID for which the description is to be retrieved\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The description associated with the ID, or null if not found or in case of an error\&. 
.RE
.PP

.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Database\&.getNameById (String id)"
Retrieves the name associated with a given ID from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP The ID for which the name is to be retrieved\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The name associated with the ID, or null if not found or in case of an error\&. 
.RE
.PP

.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Database\&.getRoomLookById (String id)"
Retrieves the room look associated with a given ID from the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP The ID for which the room look is to be retrieved\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The room look associated with the ID, or null if not found or in case of an error\&. 
.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Database\&.insertNewData ()"
Inserts new data into the database by prompting the user for input\&. Data includes ID, name, description, and room look\&.
.PP
\fBReturns\fP
.RS 4
true if the data was successfully inserted, false otherwise\&. 
.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Database\&.updateDescriptionById (String id, String newDescription)"
Updates the description associated with a given ID in the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP The ID for which the description is to be updated\&. 
.br
\fInewDescription\fP The new description to be set\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if the update was successful, false otherwise\&. 
.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Database\&.updateNameById (String id, String newName)"
Updates the name associated with a given ID in the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP The ID for which the name is to be updated\&. 
.br
\fInewName\fP The new name to be set\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if the update was successful, false otherwise\&. 
.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Database\&.updateRoomLookById (String id, String newRoomLook)"
Updates the room look associated with a given ID in the database\&. 
.PP
\fBParameters\fP
.RS 4
\fIid\fP The ID for which the room look is to be updated\&. 
.br
\fInewRoomLook\fP The new room look to be set\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if the update was successful, false otherwise\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
