.TH "di.uniba.map.b.adventure.impl.SaveGame" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.impl.SaveGame
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsave\fP (\fBRoom\fP currentRoom, List< \fBAdvObject\fP > inventory, String gameName, int elapsedSeconds, boolean monsterAlive, boolean isDoorOpen)"
.br
.ti -1c
.RI "static boolean \fBgameExists\fP (String gameName)"
.br
.ti -1c
.RI "static Map< String, Object > \fBload\fP (String gameName)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides functionality to save and load game states to and from a file\&. This class includes methods to save the current game state, check if a game save exists, and load a game state from a file\&. 
.SH "Member Function Documentation"
.PP 
.SS "static boolean di\&.uniba\&.map\&.b\&.adventure\&.impl\&.SaveGame\&.gameExists (String gameName)\fR [static]\fP"
Checks if a game save with the specified name already exists in the file\&.
.PP
\fBParameters\fP
.RS 4
\fIgameName\fP The name of the game to check\&. 
.RE
.PP
\fBReturns\fP
.RS 4
true if the game exists, false otherwise\&. 
.RE
.PP

.SS "static Map< String, Object > di\&.uniba\&.map\&.b\&.adventure\&.impl\&.SaveGame\&.load (String gameName)\fR [static]\fP"
Loads the game state from a file based on the specified game name\&. This method reads the file and constructs a map containing the game state, including elapsed seconds, current room, monster alive status, door open status, and player inventory\&.
.PP
\fBParameters\fP
.RS 4
\fIgameName\fP The name of the game to load\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A map containing the loaded game state\&. 
.RE
.PP

.SS "static void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.SaveGame\&.save (\fBRoom\fP currentRoom, List< \fBAdvObject\fP > inventory, String gameName, int elapsedSeconds, boolean monsterAlive, boolean isDoorOpen)\fR [static]\fP"
Saves the current game state to a file\&. This includes the current room, player inventory, game name, elapsed time, monster alive status, and door open status\&. If a game with the same name already exists, the save is aborted\&.
.PP
\fBParameters\fP
.RS 4
\fIcurrentRoom\fP The current room the player is in\&. 
.br
\fIinventory\fP The current inventory of the player\&. 
.br
\fIgameName\fP The name of the game save\&. 
.br
\fIelapsedSeconds\fP The elapsed time in seconds since the game started\&. 
.br
\fImonsterAlive\fP The alive status of the monster\&. 
.br
\fIisDoorOpen\fP The open status of the door\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
