.TH "di.uniba.map.b.adventure.impl.RESTClient" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.impl.RESTClient
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRESTClient\fP ()"
.br
.ti -1c
.RI "void \fBaddPlayer\fP (\fBPlayerData\fP player)"
.br
.ti -1c
.RI "String \fBgetLeaderboard\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
A client for interacting with a RESTful service, specifically designed for managing a game's leaderboard\&. This client allows for adding player data to the leaderboard and retrieving the current leaderboard standings\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "di\&.uniba\&.map\&.b\&.adventure\&.impl\&.RESTClient\&.RESTClient ()"
Constructs a new \fBRESTClient\fP instance, initializing the REST client, target URL, and Gson parser\&. 
.SH "Member Function Documentation"
.PP 
.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.RESTClient\&.addPlayer (\fBPlayerData\fP player)"
Adds a player's data to the leaderboard by sending a PUT request to the RESTful service\&. The player's data is serialized to JSON format before being sent\&.
.PP
\fBParameters\fP
.RS 4
\fIplayer\fP The player data to add to the leaderboard\&. 
.RE
.PP

.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.RESTClient\&.getLeaderboard ()"
Retrieves the current leaderboard standings by sending a GET request to the RESTful service\&. The response is deserialized from JSON format into a human-readable string\&.
.PP
\fBReturns\fP
.RS 4
A string representation of the leaderboard standings\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
