.TH "di.uniba.map.b.adventure.Utils" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.Utils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Set< String > \fBloadFileListInSet\fP (File file)  throws IOException "
.br
.ti -1c
.RI "static List< String > \fBparseString\fP (String string, Set< String > stopwords)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility class providing static methods for common operations such as loading a list of strings from a file into a set and parsing strings into a list of tokens\&. 
.SH "Member Function Documentation"
.PP 
.SS "static Set< String > di\&.uniba\&.map\&.b\&.adventure\&.Utils\&.loadFileListInSet (File file) throws IOException\fR [static]\fP"
Loads each line from a specified file into a \fR\fBSet\fP\fP of strings\&. This method is useful for loading data where each line represents a unique entry, such as a list of stopwords\&.
.PP
\fBParameters\fP
.RS 4
\fIfile\fP The file to read from\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A \fR\fBSet\fP\fP containing all lines from the file, trimmed and converted to lowercase\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs reading from the file\&. 
.RE
.PP

.SS "static List< String > di\&.uniba\&.map\&.b\&.adventure\&.Utils\&.parseString (String string, Set< String > stopwords)\fR [static]\fP"
Parses a given string into a list of tokens (words), excluding any tokens that are contained in a provided set of stopwords\&. This method is useful for text processing tasks such as tokenization\&.
.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string to parse\&. 
.br
\fIstopwords\fP A \fR\fBSet\fP\fP of stopwords to exclude from the resulting list of tokens\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A \fR\fBList\fP\fP of tokens derived from the input string, excluding any stopwords\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
