.TH "di.uniba.map.b.adventure.impl.Window" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.impl.Window
.SH SYNOPSIS
.br
.PP
.PP
Inherits JFrame\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP (\fBGameDescription\fP game, \fBParser\fP parser)"
.br
.ti -1c
.RI "void \fBshowStartDescription\fP (String startDescription)"
.br
.ti -1c
.RI "void \fBshowRoomName\fP (String roomName)"
.br
.ti -1c
.RI "void \fBshowRoomDescription\fP (String roomDescription)"
.br
.ti -1c
.RI "void \fBshowMessage\fP (String message)"
.br
.ti -1c
.RI "void \fBshowLeaderBoard\fP ()"
.br
.ti -1c
.RI "String \fBgetInsertText\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The main window for the adventure game, providing the graphical user interface\&. This class extends JFrame, incorporating various UI components to interact with the game\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Window\&.Window (\fBGameDescription\fP game, \fBParser\fP parser)"
Constructs the main game window, initializing UI components and setting up event listeners\&. 
.PP
\fBParameters\fP
.RS 4
\fIgame\fP The game description, containing the state and logic of the adventure game\&. 
.br
\fIparser\fP The parser used to interpret player commands\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Window\&.getInsertText ()"
Retrieves the text currently inserted by the player\&. 
.PP
\fBReturns\fP
.RS 4
The text inserted by the player\&. 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Window\&.showLeaderBoard ()"
Fetches and displays the leaderboard from a RESTful service\&. 
.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Window\&.showMessage (String message)"
Displays a message in a text area, typically used for feedback or game instructions\&. 
.PP
\fBParameters\fP
.RS 4
\fImessage\fP The message to display\&. 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Window\&.showRoomDescription (String roomDescription)"
Updates and displays the description of the current room in a text area\&. 
.PP
\fBParameters\fP
.RS 4
\fIroomDescription\fP The description of the current room\&. 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Window\&.showRoomName (String roomName)"
Updates and displays the name of the current room in a text area\&. 
.PP
\fBParameters\fP
.RS 4
\fIroomName\fP The name of the current room\&. 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.Window\&.showStartDescription (String startDescription)"
Displays the starting description of the game in a text area\&. 
.PP
\fBParameters\fP
.RS 4
\fIstartDescription\fP The starting description text\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
