.TH "di.uniba.map.b.adventure.type.Inventory" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.type.Inventory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< \fBAdvObject\fP > \fBgetList\fP ()"
.br
.ti -1c
.RI "void \fBsetList\fP (List< \fBAdvObject\fP > list)"
.br
.ti -1c
.RI "void \fBadd\fP (\fBAdvObject\fP o)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBAdvObject\fP o)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
sangiovannesi 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.Inventory\&.add (\fBAdvObject\fP o)"

.PP
\fBParameters\fP
.RS 4
\fIo\fP 
.RE
.PP

.SS "List< \fBAdvObject\fP > di\&.uniba\&.map\&.b\&.adventure\&.type\&.Inventory\&.getList ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.Inventory\&.remove (\fBAdvObject\fP o)"

.PP
\fBParameters\fP
.RS 4
\fIo\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.Inventory\&.setList (List< \fBAdvObject\fP > list)"

.PP
\fBParameters\fP
.RS 4
\fIlist\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
