.TH "di.uniba.map.b.adventure.parser.ParserOutput" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.parser.ParserOutput
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParserOutput\fP (\fBCommand\fP command, \fBAdvObject\fP object)"
.br
.ti -1c
.RI "\fBParserOutput\fP (\fBCommand\fP command, \fBAdvObject\fP object, \fBAdvObject\fP invObejct)"
.br
.ti -1c
.RI "\fBCommand\fP \fBgetCommand\fP ()"
.br
.ti -1c
.RI "void \fBsetCommand\fP (\fBCommand\fP command)"
.br
.ti -1c
.RI "\fBAdvObject\fP \fBgetObject\fP ()"
.br
.ti -1c
.RI "void \fBsetObject\fP (\fBAdvObject\fP object)"
.br
.ti -1c
.RI "\fBAdvObject\fP \fBgetInvObject\fP ()"
.br
.ti -1c
.RI "void \fBsetInvObject\fP (\fBAdvObject\fP invObject)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
sangiovannesi 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "di\&.uniba\&.map\&.b\&.adventure\&.parser\&.ParserOutput\&.ParserOutput (\fBCommand\fP command, \fBAdvObject\fP object)"

.PP
\fBParameters\fP
.RS 4
\fIcommand\fP 
.br
\fIobject\fP 
.RE
.PP

.SS "di\&.uniba\&.map\&.b\&.adventure\&.parser\&.ParserOutput\&.ParserOutput (\fBCommand\fP command, \fBAdvObject\fP object, \fBAdvObject\fP invObejct)"

.PP
\fBParameters\fP
.RS 4
\fIcommand\fP 
.br
\fIobject\fP 
.br
\fIinvObejct\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "\fBCommand\fP di\&.uniba\&.map\&.b\&.adventure\&.parser\&.ParserOutput\&.getCommand ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "\fBAdvObject\fP di\&.uniba\&.map\&.b\&.adventure\&.parser\&.ParserOutput\&.getInvObject ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "\fBAdvObject\fP di\&.uniba\&.map\&.b\&.adventure\&.parser\&.ParserOutput\&.getObject ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.parser\&.ParserOutput\&.setCommand (\fBCommand\fP command)"

.PP
\fBParameters\fP
.RS 4
\fIcommand\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.parser\&.ParserOutput\&.setInvObject (\fBAdvObject\fP invObject)"

.PP
\fBParameters\fP
.RS 4
\fIinvObject\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.parser\&.ParserOutput\&.setObject (\fBAdvObject\fP object)"

.PP
\fBParameters\fP
.RS 4
\fIobject\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
