.TH "di.uniba.map.b.adventure.type.AdvObject" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.type.AdvObject
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBdi\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObjectContainer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdvObject\fP (int id)"
.br
.ti -1c
.RI "\fBAdvObject\fP (int id, String name)"
.br
.ti -1c
.RI "\fBAdvObject\fP (int id, String name, String description)"
.br
.ti -1c
.RI "\fBAdvObject\fP (int id, String name, String description, Set< String > alias)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetDescription\fP ()"
.br
.ti -1c
.RI "void \fBsetDescription\fP (String description)"
.br
.ti -1c
.RI "boolean \fBisOpenable\fP ()"
.br
.ti -1c
.RI "void \fBsetOpenable\fP (boolean openable)"
.br
.ti -1c
.RI "boolean \fBisPickupable\fP ()"
.br
.ti -1c
.RI "void \fBsetPickupable\fP (boolean pickupable)"
.br
.ti -1c
.RI "boolean \fBisPushable\fP ()"
.br
.ti -1c
.RI "void \fBsetPushable\fP (boolean pushable)"
.br
.ti -1c
.RI "boolean \fBisOpen\fP ()"
.br
.ti -1c
.RI "void \fBsetOpen\fP (boolean open)"
.br
.ti -1c
.RI "boolean \fBisPush\fP ()"
.br
.ti -1c
.RI "void \fBsetPush\fP (boolean push)"
.br
.ti -1c
.RI "Set< String > \fBgetAlias\fP ()"
.br
.ti -1c
.RI "void \fBsetAlias\fP (Set< String > alias)"
.br
.ti -1c
.RI "void \fBsetAlias\fP (String[] alias)"
.br
.ti -1c
.RI "int \fBgetId\fP ()"
.br
.ti -1c
.RI "boolean \fBisCreature\fP ()"
.br
.ti -1c
.RI "void \fBsetCreature\fP (boolean creature)"
.br
.ti -1c
.RI "boolean \fBisLiving\fP ()"
.br
.ti -1c
.RI "void \fBsetLiving\fP (boolean living)"
.br
.ti -1c
.RI "boolean \fBisReadable\fP ()"
.br
.ti -1c
.RI "void \fBsetReadable\fP (boolean readable)"
.br
.ti -1c
.RI "void \fBsetContents\fP (String contents)"
.br
.ti -1c
.RI "String \fBgetContents\fP ()"
.br
.ti -1c
.RI "int \fBhashCode\fP ()"
.br
.ti -1c
.RI "boolean \fBequals\fP (Object obj)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
sangiovannesi 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.AdvObject (int id)"

.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.RE
.PP

.SS "di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.AdvObject (int id, String name)"

.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.br
\fIname\fP 
.RE
.PP

.SS "di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.AdvObject (int id, String name, String description)"

.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.br
\fIname\fP 
.br
\fIdescription\fP 
.RE
.PP

.SS "di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.AdvObject (int id, String name, String description, Set< String > alias)"

.PP
\fBParameters\fP
.RS 4
\fIid\fP 
.br
\fIname\fP 
.br
\fIdescription\fP 
.br
\fIalias\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.equals (Object obj)"

.PP
\fBParameters\fP
.RS 4
\fIobj\fP 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.SS "Set< String > di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.getAlias ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "String di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.getContents ()"

.PP
\fBReturns\fP
.RS 4
contents 
.RE
.PP

.SS "String di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.getDescription ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "int di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.getId ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "String di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.getName ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "int di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.hashCode ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.isCreature ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.isLiving ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.isOpen ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.PP
Reimplemented in \fBdi\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObjectContainer\fP\&.
.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.isOpenable ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.isPickupable ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.isPush ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.isPushable ()"

.PP
\fBReturns\fP
.RS 4

.RE
.PP

.SS "boolean di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.isReadable ()"

.PP
\fBReturns\fP
.RS 4
readable 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setAlias (Set< String > alias)"

.PP
\fBParameters\fP
.RS 4
\fIalias\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setAlias (String[] alias)"

.PP
\fBParameters\fP
.RS 4
\fIalias\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setContents (String contents)"

.PP
\fBParameters\fP
.RS 4
\fIcontents\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setCreature (boolean creature)"

.PP
\fBParameters\fP
.RS 4
\fIcreature\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setDescription (String description)"

.PP
\fBParameters\fP
.RS 4
\fIdescription\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setLiving (boolean living)"

.PP
\fBParameters\fP
.RS 4
\fIliving\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setName (String name)"

.PP
\fBParameters\fP
.RS 4
\fIname\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setOpen (boolean open)"

.PP
\fBParameters\fP
.RS 4
\fIopen\fP 
.RE
.PP

.PP
Reimplemented in \fBdi\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObjectContainer\fP\&.
.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setOpenable (boolean openable)"

.PP
\fBParameters\fP
.RS 4
\fIopenable\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setPickupable (boolean pickupable)"

.PP
\fBParameters\fP
.RS 4
\fIpickupable\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setPush (boolean push)"

.PP
\fBParameters\fP
.RS 4
\fIpush\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setPushable (boolean pushable)"

.PP
\fBParameters\fP
.RS 4
\fIpushable\fP 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.type\&.AdvObject\&.setReadable (boolean readable)"

.PP
\fBParameters\fP
.RS 4
\fIreadable\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
