.TH "di.uniba.map.b.adventure.impl.PlayerData" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.impl.PlayerData
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlayerData\fP (String name, String date, String time)"
.br
.ti -1c
.RI "String \fBgetName\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (String name)"
.br
.ti -1c
.RI "String \fBgetDate\fP ()"
.br
.ti -1c
.RI "void \fBsetDate\fP (String date)"
.br
.ti -1c
.RI "String \fBgetTime\fP ()"
.br
.ti -1c
.RI "void \fBsetTime\fP (String time)"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the data of a player in the game, including their name, the date, and the time\&. This class is used to manage player-specific information that can be utilized throughout the game\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "di\&.uniba\&.map\&.b\&.adventure\&.impl\&.PlayerData\&.PlayerData (String name, String date, String time)"
Constructs a new \fBPlayerData\fP instance with specified name, date, and time\&.
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the player\&. 
.br
\fIdate\fP The date related to the player's progress or state\&. 
.br
\fItime\fP The time related to the player's progress or state\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.PlayerData\&.getDate ()"
Gets the date associated with the player's current state or progress\&.
.PP
\fBReturns\fP
.RS 4
The date related to the player's progress or state\&. 
.RE
.PP

.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.PlayerData\&.getName ()"
Gets the player's name\&.
.PP
\fBReturns\fP
.RS 4
The name of the player\&. 
.RE
.PP

.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.PlayerData\&.getTime ()"
Gets the time associated with the player's current state or progress\&.
.PP
\fBReturns\fP
.RS 4
The time related to the player's progress or state\&. 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.PlayerData\&.setDate (String date)"
Sets the date associated with the player's current state or progress\&.
.PP
\fBParameters\fP
.RS 4
\fIdate\fP The new date related to the player's progress or state\&. 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.PlayerData\&.setName (String name)"
Sets the player's name\&.
.PP
\fBParameters\fP
.RS 4
\fIname\fP The new name of the player\&. 
.RE
.PP

.SS "void di\&.uniba\&.map\&.b\&.adventure\&.impl\&.PlayerData\&.setTime (String time)"
Sets the time associated with the player's current state or progress\&.
.PP
\fBParameters\fP
.RS 4
\fItime\fP The new time related to the player's progress or state\&. 
.RE
.PP

.SS "String di\&.uniba\&.map\&.b\&.adventure\&.impl\&.PlayerData\&.toString ()"
Returns a string representation of the player data, including name, date, and time\&.
.PP
\fBReturns\fP
.RS 4
A string representation of the player data\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
