.TH "di.uniba.map.b.adventure.GameUtils" 3 "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
di.uniba.map.b.adventure.GameUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBAdvObject\fP \fBgetObjectFromInventory\fP (List< \fBAdvObject\fP > inventory, int id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility class containing helper methods for game operations\&. 
.SH "Member Function Documentation"
.PP 
.SS "static \fBAdvObject\fP di\&.uniba\&.map\&.b\&.adventure\&.GameUtils\&.getObjectFromInventory (List< \fBAdvObject\fP > inventory, int id)\fR [static]\fP"
Searches for an object in the player's inventory by its ID\&.
.PP
\fBParameters\fP
.RS 4
\fIinventory\fP The list of \fR\fBAdvObject\fP\fP representing the player's inventory\&. 
.br
\fIid\fP The unique identifier of the object to search for\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The \fR\fBAdvObject\fP\fP if found in the inventory; otherwise, returns \fR
null\fP
\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
